apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.namespace }}-db-migration
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.namespace }}-db-migration
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              {{ .Values.commands.migrate }} && \
              {{ .Values.commands.seed }}
          env:
          envFrom:
          - secretRef:
              name: {{ .Values.namespace }}-app-secret
      restartPolicy: Never