apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.namespace }}-db-migration
  namespace: {{ .Values.namespace }}
spec:
  schedule: '* * * * *'   
  suspend: true           
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1    
  jobTemplate:
    spec:
      backoffLimit: 0  
      template:
        spec:
          containers:
            - name: {{ .Values.namespace }}-db-migration
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              command: ["/bin/sh", "-c"]
              args:
                - |
                  {{ .Values.commands.migrate }} && \
                  {{ .Values.commands.seed }}
              envFrom:
                - secretRef:
                    name: {{ .Values.namespace }}-app-secret
          restartPolicy: Never 
