apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namespace }}-app-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.namespace }}-app
type: {{ .Values.secret.type }}
data:
  username: {{ default "" .Values.secret.db.username | b64enc | quote }}
  password: {{ default "" .Values.secret.db.password | b64enc | quote }}
  database: {{ default "" .Values.secret.db.database | b64enc | quote }}
  host: {{ default "" .Values.secret.db.host | b64enc | quote }}
  port: {{ default "" .Values.secret.db.port | b64enc | quote }}